### PR TITLE
Fixed input from zbarcam

### PR DESCRIPTION
**Pull request by rbicelli**
With these changes zbarcam input is processed correctly. Needs to read standard input line by line and leave the program running while zbarcam is running.

### CODE REVIEW

**Comment by berdav** [comment]
Thank you for your interest, the problem is still present using the `-1` switch of zbarcam? (as stated in https://github.com/berdav/greenpass/issues/4 and https://github.com/berdav/greenpass/issues/6 )

If this is not the case I think that using a special file input will introduce some clashes if someone uses a file called "loopinput" but I would prefer to use a switch to the script.

**Comment by rbicelli** [comment]
Yes, it's a dirty fix, maybe an --feed switch or similar would be better.

(Greetings for is_aladeen test case, I laughed)

Il Mar 21 Set 2021, 13:00 Davide Berardi ***@***.***> ha
scritto:

**Comment by berdav** [comment]
I think that using the current master (5b74940aeb2e5b4c7c0ef7d07fca25e89953cc16) would be sufficient, can you check it?

that invalidates the behaviour having a feed of greenpass on the pipe but I think it will be sufficient.

I'm also posting this in the issue.

(thank you for the is_aladeen, I think it should be included in every test ;D)

**Comment by rbicelli** [comment]
I made that fix for a protoype I was writing.
Reading through your code I found that I have to make some changes to adapt to my needs:

- separate the decoding part from the parsing/validating part: using the program with zbarcam/openCV it doesn't make sense to have the qr/pdf/txt decoder embedded in the parser: it's best to have a decoder which decodes the payload and pass it to the parser
- cache the requests responses for settings and keys: at first run will cache the request results in a temp file and use them until they expire (with customizable expiration time)

With these small chenges it could be used also as a library for other python programs, or at least for mine.

So for now I'll keep my fork.

**Comment by berdav** [comment]
That are some nice ideas,

I'll open two issues with that ideas, if you want to work on them you're really welcome to do so.

**Comment by berdav** [comment]
Closing, the current master is now a library, should be possible to do what you're describing in this pull request.

Thank you, if something do not work let me know.

**Pull request closed without merging**
